package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccionistaId generated by hbm2java
 */
@Embeddable
public class AccionistaId implements java.io.Serializable {

	private String ruc;
	private String dni;

	public AccionistaId() {
	}

	public AccionistaId(String ruc, String dni) {
		this.ruc = ruc;
		this.dni = dni;
	}

	@Column(name = "ruc", nullable = false, length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@Column(name = "dni", nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccionistaId))
			return false;
		AccionistaId castOther = (AccionistaId) other;

		return ((this.getRuc() == castOther.getRuc()) || (this.getRuc() != null
				&& castOther.getRuc() != null && this.getRuc().equals(
				castOther.getRuc())))
				&& ((this.getDni() == castOther.getDni()) || (this.getDni() != null
						&& castOther.getDni() != null && this.getDni().equals(
						castOther.getDni())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRuc() == null ? 0 : this.getRuc().hashCode());
		result = 37 * result
				+ (getDni() == null ? 0 : this.getDni().hashCode());
		return result;
	}

}
