package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Accionista generated by hbm2java
 */
@Entity
@Table(name = "accionista", schema = "persona")
public class Accionista implements java.io.Serializable {

	private AccionistaId id;
	private Personajuridica personajuridica;
	private Personanatural personanatural;
	private double porcentajeparticipacion;
	private boolean estado;

	public Accionista() {
	}

	public Accionista(AccionistaId id, Personajuridica personajuridica,
			Personanatural personanatural, double porcentajeparticipacion,
			boolean estado) {
		this.id = id;
		this.personajuridica = personajuridica;
		this.personanatural = personanatural;
		this.porcentajeparticipacion = porcentajeparticipacion;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ruc", column = @Column(name = "ruc", nullable = false, length = 11)),
			@AttributeOverride(name = "dni", column = @Column(name = "dni", nullable = false, length = 8)) })
	public AccionistaId getId() {
		return this.id;
	}

	public void setId(AccionistaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ruc", nullable = false, insertable = false, updatable = false)
	public Personajuridica getPersonajuridica() {
		return this.personajuridica;
	}

	public void setPersonajuridica(Personajuridica personajuridica) {
		this.personajuridica = personajuridica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni", nullable = false, insertable = false, updatable = false)
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@Column(name = "porcentajeparticipacion", nullable = false, precision = 17, scale = 17)
	public double getPorcentajeparticipacion() {
		return this.porcentajeparticipacion;
	}

	public void setPorcentajeparticipacion(double porcentajeparticipacion) {
		this.porcentajeparticipacion = porcentajeparticipacion;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
