package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BeneficiariocuentaId generated by hbm2java
 */
@Embeddable
public class BeneficiariocuentaId implements java.io.Serializable {

	private String dni;
	private String numerocuentaahorro;
	private double porcentajebeneficio;
	private String numerocuentacorriente;
	private String numerocuentaplazofijo;
	private int idbeneficiariocuenta;

	public BeneficiariocuentaId() {
	}

	public BeneficiariocuentaId(String dni, String numerocuentaahorro,
			double porcentajebeneficio, int idbeneficiariocuenta) {
		this.dni = dni;
		this.numerocuentaahorro = numerocuentaahorro;
		this.porcentajebeneficio = porcentajebeneficio;
		this.idbeneficiariocuenta = idbeneficiariocuenta;
	}

	public BeneficiariocuentaId(String dni, String numerocuentaahorro,
			double porcentajebeneficio, String numerocuentacorriente,
			String numerocuentaplazofijo, int idbeneficiariocuenta) {
		this.dni = dni;
		this.numerocuentaahorro = numerocuentaahorro;
		this.porcentajebeneficio = porcentajebeneficio;
		this.numerocuentacorriente = numerocuentacorriente;
		this.numerocuentaplazofijo = numerocuentaplazofijo;
		this.idbeneficiariocuenta = idbeneficiariocuenta;
	}

	@Column(name = "dni", nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@Column(name = "numerocuentaahorro", nullable = false, length = 14)
	public String getNumerocuentaahorro() {
		return this.numerocuentaahorro;
	}

	public void setNumerocuentaahorro(String numerocuentaahorro) {
		this.numerocuentaahorro = numerocuentaahorro;
	}

	@Column(name = "porcentajebeneficio", nullable = false, precision = 17, scale = 17)
	public double getPorcentajebeneficio() {
		return this.porcentajebeneficio;
	}

	public void setPorcentajebeneficio(double porcentajebeneficio) {
		this.porcentajebeneficio = porcentajebeneficio;
	}

	@Column(name = "numerocuentacorriente", length = 14)
	public String getNumerocuentacorriente() {
		return this.numerocuentacorriente;
	}

	public void setNumerocuentacorriente(String numerocuentacorriente) {
		this.numerocuentacorriente = numerocuentacorriente;
	}

	@Column(name = "numerocuentaplazofijo", length = 14)
	public String getNumerocuentaplazofijo() {
		return this.numerocuentaplazofijo;
	}

	public void setNumerocuentaplazofijo(String numerocuentaplazofijo) {
		this.numerocuentaplazofijo = numerocuentaplazofijo;
	}

	@Column(name = "idbeneficiariocuenta", nullable = false)
	public int getIdbeneficiariocuenta() {
		return this.idbeneficiariocuenta;
	}

	public void setIdbeneficiariocuenta(int idbeneficiariocuenta) {
		this.idbeneficiariocuenta = idbeneficiariocuenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BeneficiariocuentaId))
			return false;
		BeneficiariocuentaId castOther = (BeneficiariocuentaId) other;

		return ((this.getDni() == castOther.getDni()) || (this.getDni() != null
				&& castOther.getDni() != null && this.getDni().equals(
				castOther.getDni())))
				&& ((this.getNumerocuentaahorro() == castOther
						.getNumerocuentaahorro()) || (this
						.getNumerocuentaahorro() != null
						&& castOther.getNumerocuentaahorro() != null && this
						.getNumerocuentaahorro().equals(
								castOther.getNumerocuentaahorro())))
				&& (this.getPorcentajebeneficio() == castOther
						.getPorcentajebeneficio())
				&& ((this.getNumerocuentacorriente() == castOther
						.getNumerocuentacorriente()) || (this
						.getNumerocuentacorriente() != null
						&& castOther.getNumerocuentacorriente() != null && this
						.getNumerocuentacorriente().equals(
								castOther.getNumerocuentacorriente())))
				&& ((this.getNumerocuentaplazofijo() == castOther
						.getNumerocuentaplazofijo()) || (this
						.getNumerocuentaplazofijo() != null
						&& castOther.getNumerocuentaplazofijo() != null && this
						.getNumerocuentaplazofijo().equals(
								castOther.getNumerocuentaplazofijo())))
				&& (this.getIdbeneficiariocuenta() == castOther
						.getIdbeneficiariocuenta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getDni() == null ? 0 : this.getDni().hashCode());
		result = 37
				* result
				+ (getNumerocuentaahorro() == null ? 0 : this
						.getNumerocuentaahorro().hashCode());
		result = 37 * result + (int) this.getPorcentajebeneficio();
		result = 37
				* result
				+ (getNumerocuentacorriente() == null ? 0 : this
						.getNumerocuentacorriente().hashCode());
		result = 37
				* result
				+ (getNumerocuentaplazofijo() == null ? 0 : this
						.getNumerocuentaplazofijo().hashCode());
		result = 37 * result + this.getIdbeneficiariocuenta();
		return result;
	}

}
