package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Beneficiariocuenta generated by hbm2java
 */
@Entity
@Table(name = "beneficiariocuenta", schema = "cuentapersonal")
public class Beneficiariocuenta implements java.io.Serializable {

	private BeneficiariocuentaId id;
	private Cuentaplazofijo cuentaplazofijo;
	private Cuentacorriente cuentacorriente;
	private Personanatural personanatural;
	private Cuentaahorro cuentaahorro;

	public Beneficiariocuenta() {
	}

	public Beneficiariocuenta(BeneficiariocuentaId id,
			Personanatural personanatural, Cuentaahorro cuentaahorro) {
		this.id = id;
		this.personanatural = personanatural;
		this.cuentaahorro = cuentaahorro;
	}

	public Beneficiariocuenta(BeneficiariocuentaId id,
			Cuentaplazofijo cuentaplazofijo, Cuentacorriente cuentacorriente,
			Personanatural personanatural, Cuentaahorro cuentaahorro) {
		this.id = id;
		this.cuentaplazofijo = cuentaplazofijo;
		this.cuentacorriente = cuentacorriente;
		this.personanatural = personanatural;
		this.cuentaahorro = cuentaahorro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dni", column = @Column(name = "dni", nullable = false, length = 8)),
			@AttributeOverride(name = "numerocuentaahorro", column = @Column(name = "numerocuentaahorro", nullable = false, length = 14)),
			@AttributeOverride(name = "porcentajebeneficio", column = @Column(name = "porcentajebeneficio", nullable = false, precision = 17, scale = 17)),
			@AttributeOverride(name = "numerocuentacorriente", column = @Column(name = "numerocuentacorriente", length = 14)),
			@AttributeOverride(name = "numerocuentaplazofijo", column = @Column(name = "numerocuentaplazofijo", length = 14)),
			@AttributeOverride(name = "idbeneficiariocuenta", column = @Column(name = "idbeneficiariocuenta", nullable = false)) })
	public BeneficiariocuentaId getId() {
		return this.id;
	}

	public void setId(BeneficiariocuentaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaplazofijo", insertable = false, updatable = false)
	public Cuentaplazofijo getCuentaplazofijo() {
		return this.cuentaplazofijo;
	}

	public void setCuentaplazofijo(Cuentaplazofijo cuentaplazofijo) {
		this.cuentaplazofijo = cuentaplazofijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentacorriente", insertable = false, updatable = false)
	public Cuentacorriente getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(Cuentacorriente cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni", nullable = false, insertable = false, updatable = false)
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaahorro", nullable = false, insertable = false, updatable = false)
	public Cuentaahorro getCuentaahorro() {
		return this.cuentaahorro;
	}

	public void setCuentaahorro(Cuentaahorro cuentaahorro) {
		this.cuentaahorro = cuentaahorro;
	}

}
