package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cheque generated by hbm2java
 */
@Entity
@Table(name = "cheque", schema = "cuentapersonal")
public class Cheque implements java.io.Serializable {

	private ChequeId id;
	private Chequeestado chequeestado;
	private Chequera chequera;

	public Cheque() {
	}

	public Cheque(ChequeId id, Chequeestado chequeestado, Chequera chequera) {
		this.id = id;
		this.chequeestado = chequeestado;
		this.chequera = chequera;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numerochequeraporcliente", column = @Column(name = "numerochequeraporcliente", nullable = false, length = 14)),
			@AttributeOverride(name = "numerocheque", column = @Column(name = "numerocheque", nullable = false)) })
	public ChequeId getId() {
		return this.id;
	}

	public void setId(ChequeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocheque", nullable = false)
	public Chequeestado getChequeestado() {
		return this.chequeestado;
	}

	public void setChequeestado(Chequeestado chequeestado) {
		this.chequeestado = chequeestado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "numerocuentacorriente", referencedColumnName = "numerochequeraporcliente", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "numerochequeraporcliente", referencedColumnName = "numerocuentacorriente", nullable = false, insertable = false, updatable = false) })
	public Chequera getChequera() {
		return this.chequera;
	}

	public void setChequera(Chequera chequera) {
		this.chequera = chequera;
	}

}
