package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chequeraestado generated by hbm2java
 */
@Entity
@Table(name = "chequeraestado", schema = "cuentapersonal")
public class Chequeraestado implements java.io.Serializable {

	private int idchequeraestado;
	private int denominacion;
	private String abreviatura;
	private boolean estado;
	private Set chequeras = new HashSet(0);

	public Chequeraestado() {
	}

	public Chequeraestado(int idchequeraestado, int denominacion, boolean estado) {
		this.idchequeraestado = idchequeraestado;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Chequeraestado(int idchequeraestado, int denominacion,
			String abreviatura, boolean estado, Set chequeras) {
		this.idchequeraestado = idchequeraestado;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.chequeras = chequeras;
	}

	@Id
	@Column(name = "idchequeraestado", unique = true, nullable = false)
	public int getIdchequeraestado() {
		return this.idchequeraestado;
	}

	public void setIdchequeraestado(int idchequeraestado) {
		this.idchequeraestado = idchequeraestado;
	}

	@Column(name = "denominacion", nullable = false)
	public int getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(int denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 2)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chequeraestado")
	public Set getChequeras() {
		return this.chequeras;
	}

	public void setChequeras(Set chequeras) {
		this.chequeras = chequeras;
	}

}
