package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChequeId generated by hbm2java
 */
@Embeddable
public class ChequeId implements java.io.Serializable {

	private int numerochequeraporcliente;
	private int numerocheque;

	public ChequeId() {
	}

	public ChequeId(int numerochequeraporcliente, int numerocheque) {
		this.numerochequeraporcliente = numerochequeraporcliente;
		this.numerocheque = numerocheque;
	}

	@Column(name = "numerochequeraporcliente", nullable = false, length = 14)
	public int getNumerochequeraporcliente() {
		return this.numerochequeraporcliente;
	}

	public void setNumerochequeraporcliente(int numerochequeraporcliente) {
		this.numerochequeraporcliente = numerochequeraporcliente;
	}

	@Column(name = "numerocheque", nullable = false)
	public int getNumerocheque() {
		return this.numerocheque;
	}

	public void setNumerocheque(int numerocheque) {
		this.numerocheque = numerocheque;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChequeId))
			return false;
		ChequeId castOther = (ChequeId) other;

		return (this.getNumerochequeraporcliente() == castOther
				.getNumerochequeraporcliente())
				&& (this.getNumerocheque() == castOther.getNumerocheque());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumerochequeraporcliente();
		result = 37 * result + this.getNumerocheque();
		return result;
	}

}
