package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chequeestado generated by hbm2java
 */
@Entity
@Table(name = "chequeestado", schema = "cuentapersonal")
public class Chequeestado implements java.io.Serializable {

	private int idchequeestado;
	private String denominacion;
	private String abreviatura;
	private boolean estado;
	private Set cheques = new HashSet(0);

	public Chequeestado() {
	}

	public Chequeestado(int idchequeestado, String denominacion, boolean estado) {
		this.idchequeestado = idchequeestado;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Chequeestado(int idchequeestado, String denominacion,
			String abreviatura, boolean estado, Set cheques) {
		this.idchequeestado = idchequeestado;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.cheques = cheques;
	}

	@Id
	@Column(name = "idchequeestado", unique = true, nullable = false)
	public int getIdchequeestado() {
		return this.idchequeestado;
	}

	public void setIdchequeestado(int idchequeestado) {
		this.idchequeestado = idchequeestado;
	}

	@Column(name = "denominacion", nullable = false, length = 50)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 2)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chequeestado")
	public Set getCheques() {
		return this.cheques;
	}

	public void setCheques(Set cheques) {
		this.cheques = cheques;
	}

}
