package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChequeraId generated by hbm2java
 */
@Embeddable
public class ChequeraId implements java.io.Serializable {

	private int numerochequeraporcliente;
	private String numerocuentacorriente;

	public ChequeraId() {
	}

	public ChequeraId(int numerochequeraporcliente, String numerocuentacorriente) {
		this.numerochequeraporcliente = numerochequeraporcliente;
		this.numerocuentacorriente = numerocuentacorriente;
	}

	@Column(name = "numerochequeraporcliente", nullable = false)
	public int getNumerochequeraporcliente() {
		return this.numerochequeraporcliente;
	}

	public void setNumerochequeraporcliente(int numerochequeraporcliente) {
		this.numerochequeraporcliente = numerochequeraporcliente;
	}

	@Column(name = "numerocuentacorriente", nullable = false, length = 14)
	public String getNumerocuentacorriente() {
		return this.numerocuentacorriente;
	}

	public void setNumerocuentacorriente(String numerocuentacorriente) {
		this.numerocuentacorriente = numerocuentacorriente;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ChequeraId))
			return false;
		ChequeraId castOther = (ChequeraId) other;

		return (this.getNumerochequeraporcliente() == castOther
				.getNumerochequeraporcliente())
				&& ((this.getNumerocuentacorriente() == castOther
						.getNumerocuentacorriente()) || (this
						.getNumerocuentacorriente() != null
						&& castOther.getNumerocuentacorriente() != null && this
						.getNumerocuentacorriente().equals(
								castOther.getNumerocuentacorriente())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumerochequeraporcliente();
		result = 37
				* result
				+ (getNumerocuentacorriente() == null ? 0 : this
						.getNumerocuentacorriente().hashCode());
		return result;
	}

}
