package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuentacorriente generated by hbm2java
 */
@Entity
@Table(name = "cuentacorriente", schema = "cuentapersonal")
public class Cuentacorriente implements java.io.Serializable {

	private String numerocuentacorriente;
	private Estadocuenta estadocuenta;
	private Personajuridicacliente personajuridicacliente;
	private Tipomoneda tipomoneda;
	private Personanaturalcliente personanaturalcliente;
	private Date fechaapertura;
	private Set titularcuentas = new HashSet(0);
	private Set cuentacorrientehistorials = new HashSet(0);
	private Set beneficiariocuentas = new HashSet(0);
	private Set chequeras = new HashSet(0);
	private Set targetadebitoasignadocuentacorrientes = new HashSet(0);

	public Cuentacorriente() {
	}

	public Cuentacorriente(String numerocuentacorriente,
			Estadocuenta estadocuenta, Tipomoneda tipomoneda, Date fechaapertura) {
		this.numerocuentacorriente = numerocuentacorriente;
		this.estadocuenta = estadocuenta;
		this.tipomoneda = tipomoneda;
		this.fechaapertura = fechaapertura;
	}

	public Cuentacorriente(String numerocuentacorriente,
			Estadocuenta estadocuenta,
			Personajuridicacliente personajuridicacliente,
			Tipomoneda tipomoneda, Personanaturalcliente personanaturalcliente,
			Date fechaapertura, Set titularcuentas,
			Set cuentacorrientehistorials, Set beneficiariocuentas,
			Set chequeras, Set targetadebitoasignadocuentacorrientes) {
		this.numerocuentacorriente = numerocuentacorriente;
		this.estadocuenta = estadocuenta;
		this.personajuridicacliente = personajuridicacliente;
		this.tipomoneda = tipomoneda;
		this.personanaturalcliente = personanaturalcliente;
		this.fechaapertura = fechaapertura;
		this.titularcuentas = titularcuentas;
		this.cuentacorrientehistorials = cuentacorrientehistorials;
		this.beneficiariocuentas = beneficiariocuentas;
		this.chequeras = chequeras;
		this.targetadebitoasignadocuentacorrientes = targetadebitoasignadocuentacorrientes;
	}

	@Id
	@Column(name = "numerocuentacorriente", unique = true, nullable = false, length = 14)
	public String getNumerocuentacorriente() {
		return this.numerocuentacorriente;
	}

	public void setNumerocuentacorriente(String numerocuentacorriente) {
		this.numerocuentacorriente = numerocuentacorriente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocuenta", nullable = false)
	public Estadocuenta getEstadocuenta() {
		return this.estadocuenta;
	}

	public void setEstadocuenta(Estadocuenta estadocuenta) {
		this.estadocuenta = estadocuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ruc")
	public Personajuridicacliente getPersonajuridicacliente() {
		return this.personajuridicacliente;
	}

	public void setPersonajuridicacliente(
			Personajuridicacliente personajuridicacliente) {
		this.personajuridicacliente = personajuridicacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipomoneda", nullable = false)
	public Tipomoneda getTipomoneda() {
		return this.tipomoneda;
	}

	public void setTipomoneda(Tipomoneda tipomoneda) {
		this.tipomoneda = tipomoneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni")
	public Personanaturalcliente getPersonanaturalcliente() {
		return this.personanaturalcliente;
	}

	public void setPersonanaturalcliente(
			Personanaturalcliente personanaturalcliente) {
		this.personanaturalcliente = personanaturalcliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaapertura", nullable = false, length = 13)
	public Date getFechaapertura() {
		return this.fechaapertura;
	}

	public void setFechaapertura(Date fechaapertura) {
		this.fechaapertura = fechaapertura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentacorriente")
	public Set getTitularcuentas() {
		return this.titularcuentas;
	}

	public void setTitularcuentas(Set titularcuentas) {
		this.titularcuentas = titularcuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentacorriente")
	public Set getCuentacorrientehistorials() {
		return this.cuentacorrientehistorials;
	}

	public void setCuentacorrientehistorials(Set cuentacorrientehistorials) {
		this.cuentacorrientehistorials = cuentacorrientehistorials;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentacorriente")
	public Set getBeneficiariocuentas() {
		return this.beneficiariocuentas;
	}

	public void setBeneficiariocuentas(Set beneficiariocuentas) {
		this.beneficiariocuentas = beneficiariocuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentacorriente")
	public Set getChequeras() {
		return this.chequeras;
	}

	public void setChequeras(Set chequeras) {
		this.chequeras = chequeras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentacorriente")
	public Set getTargetadebitoasignadocuentacorrientes() {
		return this.targetadebitoasignadocuentacorrientes;
	}

	public void setTargetadebitoasignadocuentacorrientes(
			Set targetadebitoasignadocuentacorrientes) {
		this.targetadebitoasignadocuentacorrientes = targetadebitoasignadocuentacorrientes;
	}

}
