package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuentaahorro generated by hbm2java
 */
@Entity
@Table(name = "cuentaahorro", schema = "cuentapersonal")
public class Cuentaahorro implements java.io.Serializable {

	private String numerocuentaahorro;
	private Estadocuenta estadocuenta;
	private Personajuridicacliente personajuridicacliente;
	private Tipomoneda tipomoneda;
	private Personanaturalcliente personanaturalcliente;
	private Date fechaapertura;
	private double saldo;
	private Set beneficiariocuentas = new HashSet(0);
	private Set titularcuentas = new HashSet(0);
	private Set tarjetadebitoasignadocuentaahorros = new HashSet(0);
	private Set cuentaahorrohistorials = new HashSet(0);

	public Cuentaahorro() {
	}

	public Cuentaahorro(String numerocuentaahorro, Estadocuenta estadocuenta,
			Tipomoneda tipomoneda, Date fechaapertura, double saldo) {
		this.numerocuentaahorro = numerocuentaahorro;
		this.estadocuenta = estadocuenta;
		this.tipomoneda = tipomoneda;
		this.fechaapertura = fechaapertura;
		this.saldo = saldo;
	}

	public Cuentaahorro(String numerocuentaahorro, Estadocuenta estadocuenta,
			Personajuridicacliente personajuridicacliente,
			Tipomoneda tipomoneda, Personanaturalcliente personanaturalcliente,
			Date fechaapertura, double saldo, Set beneficiariocuentas,
			Set titularcuentas, Set tarjetadebitoasignadocuentaahorros,
			Set cuentaahorrohistorials) {
		this.numerocuentaahorro = numerocuentaahorro;
		this.estadocuenta = estadocuenta;
		this.personajuridicacliente = personajuridicacliente;
		this.tipomoneda = tipomoneda;
		this.personanaturalcliente = personanaturalcliente;
		this.fechaapertura = fechaapertura;
		this.saldo = saldo;
		this.beneficiariocuentas = beneficiariocuentas;
		this.titularcuentas = titularcuentas;
		this.tarjetadebitoasignadocuentaahorros = tarjetadebitoasignadocuentaahorros;
		this.cuentaahorrohistorials = cuentaahorrohistorials;
	}

	@Id
	@Column(name = "numerocuentaahorro", unique = true, nullable = false, length = 14)
	public String getNumerocuentaahorro() {
		return this.numerocuentaahorro;
	}

	public void setNumerocuentaahorro(String numerocuentaahorro) {
		this.numerocuentaahorro = numerocuentaahorro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocuenta", nullable = false)
	public Estadocuenta getEstadocuenta() {
		return this.estadocuenta;
	}

	public void setEstadocuenta(Estadocuenta estadocuenta) {
		this.estadocuenta = estadocuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ruc")
	public Personajuridicacliente getPersonajuridicacliente() {
		return this.personajuridicacliente;
	}

	public void setPersonajuridicacliente(
			Personajuridicacliente personajuridicacliente) {
		this.personajuridicacliente = personajuridicacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipomoneda", nullable = false)
	public Tipomoneda getTipomoneda() {
		return this.tipomoneda;
	}

	public void setTipomoneda(Tipomoneda tipomoneda) {
		this.tipomoneda = tipomoneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni")
	public Personanaturalcliente getPersonanaturalcliente() {
		return this.personanaturalcliente;
	}

	public void setPersonanaturalcliente(
			Personanaturalcliente personanaturalcliente) {
		this.personanaturalcliente = personanaturalcliente;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaapertura", nullable = false, length = 13)
	public Date getFechaapertura() {
		return this.fechaapertura;
	}

	public void setFechaapertura(Date fechaapertura) {
		this.fechaapertura = fechaapertura;
	}

	@Column(name = "saldo", nullable = false, precision = 17, scale = 17)
	public double getSaldo() {
		return this.saldo;
	}

	public void setSaldo(double saldo) {
		this.saldo = saldo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaahorro")
	public Set getBeneficiariocuentas() {
		return this.beneficiariocuentas;
	}

	public void setBeneficiariocuentas(Set beneficiariocuentas) {
		this.beneficiariocuentas = beneficiariocuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaahorro")
	public Set getTitularcuentas() {
		return this.titularcuentas;
	}

	public void setTitularcuentas(Set titularcuentas) {
		this.titularcuentas = titularcuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaahorro")
	public Set getTarjetadebitoasignadocuentaahorros() {
		return this.tarjetadebitoasignadocuentaahorros;
	}

	public void setTarjetadebitoasignadocuentaahorros(
			Set tarjetadebitoasignadocuentaahorros) {
		this.tarjetadebitoasignadocuentaahorros = tarjetadebitoasignadocuentaahorros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaahorro")
	public Set getCuentaahorrohistorials() {
		return this.cuentaahorrohistorials;
	}

	public void setCuentaahorrohistorials(Set cuentaahorrohistorials) {
		this.cuentaahorrohistorials = cuentaahorrohistorials;
	}

}
