package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cuentaplazofijo generated by hbm2java
 */
@Entity
@Table(name = "cuentaplazofijo", schema = "cuentapersonal")
public class Cuentaplazofijo implements java.io.Serializable {

	private String numerocuentaplazofijo;
	private Estadocuenta estadocuenta;
	private Personajuridicacliente personajuridicacliente;
	private Tipomoneda tipomoneda;
	private Retirointeres retirointeres;
	private Personanaturalcliente personanaturalcliente;
	private Frecuenciacapitalizacion frecuenciacapitalizacion;
	private Date fechaapertura;
	private String tiporetiro;
	private BigDecimal tasainteres;
	private double ticeaf;
	private double trea;
	private double montointerespagado;
	private Date fechavencimiento;
	private double monto;
	private double itf;
	private Set beneficiariocuentas = new HashSet(0);
	private Set titularcuentas = new HashSet(0);

	public Cuentaplazofijo() {
	}

	public Cuentaplazofijo(String numerocuentaplazofijo,
			Estadocuenta estadocuenta, Tipomoneda tipomoneda,
			Retirointeres retirointeres,
			Frecuenciacapitalizacion frecuenciacapitalizacion, double ticeaf,
			double trea, double montointerespagado, Date fechavencimiento,
			double monto, double itf) {
		this.numerocuentaplazofijo = numerocuentaplazofijo;
		this.estadocuenta = estadocuenta;
		this.tipomoneda = tipomoneda;
		this.retirointeres = retirointeres;
		this.frecuenciacapitalizacion = frecuenciacapitalizacion;
		this.ticeaf = ticeaf;
		this.trea = trea;
		this.montointerespagado = montointerespagado;
		this.fechavencimiento = fechavencimiento;
		this.monto = monto;
		this.itf = itf;
	}

	public Cuentaplazofijo(String numerocuentaplazofijo,
			Estadocuenta estadocuenta,
			Personajuridicacliente personajuridicacliente,
			Tipomoneda tipomoneda, Retirointeres retirointeres,
			Personanaturalcliente personanaturalcliente,
			Frecuenciacapitalizacion frecuenciacapitalizacion,
			Date fechaapertura, String tiporetiro, BigDecimal tasainteres,
			double ticeaf, double trea, double montointerespagado,
			Date fechavencimiento, double monto, double itf,
			Set beneficiariocuentas, Set titularcuentas) {
		this.numerocuentaplazofijo = numerocuentaplazofijo;
		this.estadocuenta = estadocuenta;
		this.personajuridicacliente = personajuridicacliente;
		this.tipomoneda = tipomoneda;
		this.retirointeres = retirointeres;
		this.personanaturalcliente = personanaturalcliente;
		this.frecuenciacapitalizacion = frecuenciacapitalizacion;
		this.fechaapertura = fechaapertura;
		this.tiporetiro = tiporetiro;
		this.tasainteres = tasainteres;
		this.ticeaf = ticeaf;
		this.trea = trea;
		this.montointerespagado = montointerespagado;
		this.fechavencimiento = fechavencimiento;
		this.monto = monto;
		this.itf = itf;
		this.beneficiariocuentas = beneficiariocuentas;
		this.titularcuentas = titularcuentas;
	}

	@Id
	@Column(name = "numerocuentaplazofijo", unique = true, nullable = false, length = 14)
	public String getNumerocuentaplazofijo() {
		return this.numerocuentaplazofijo;
	}

	public void setNumerocuentaplazofijo(String numerocuentaplazofijo) {
		this.numerocuentaplazofijo = numerocuentaplazofijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocuenta", nullable = false)
	public Estadocuenta getEstadocuenta() {
		return this.estadocuenta;
	}

	public void setEstadocuenta(Estadocuenta estadocuenta) {
		this.estadocuenta = estadocuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ruc")
	public Personajuridicacliente getPersonajuridicacliente() {
		return this.personajuridicacliente;
	}

	public void setPersonajuridicacliente(
			Personajuridicacliente personajuridicacliente) {
		this.personajuridicacliente = personajuridicacliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipomoneda", nullable = false)
	public Tipomoneda getTipomoneda() {
		return this.tipomoneda;
	}

	public void setTipomoneda(Tipomoneda tipomoneda) {
		this.tipomoneda = tipomoneda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idretirointeres", nullable = false)
	public Retirointeres getRetirointeres() {
		return this.retirointeres;
	}

	public void setRetirointeres(Retirointeres retirointeres) {
		this.retirointeres = retirointeres;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni")
	public Personanaturalcliente getPersonanaturalcliente() {
		return this.personanaturalcliente;
	}

	public void setPersonanaturalcliente(
			Personanaturalcliente personanaturalcliente) {
		this.personanaturalcliente = personanaturalcliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfrecuenciacapitalizacion", nullable = false)
	public Frecuenciacapitalizacion getFrecuenciacapitalizacion() {
		return this.frecuenciacapitalizacion;
	}

	public void setFrecuenciacapitalizacion(
			Frecuenciacapitalizacion frecuenciacapitalizacion) {
		this.frecuenciacapitalizacion = frecuenciacapitalizacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaapertura", length = 13)
	public Date getFechaapertura() {
		return this.fechaapertura;
	}

	public void setFechaapertura(Date fechaapertura) {
		this.fechaapertura = fechaapertura;
	}

	@Column(name = "tiporetiro", length = 20)
	public String getTiporetiro() {
		return this.tiporetiro;
	}

	public void setTiporetiro(String tiporetiro) {
		this.tiporetiro = tiporetiro;
	}

	@Column(name = "tasainteres", precision = 131089, scale = 0)
	public BigDecimal getTasainteres() {
		return this.tasainteres;
	}

	public void setTasainteres(BigDecimal tasainteres) {
		this.tasainteres = tasainteres;
	}

	@Column(name = "ticeaf", nullable = false, precision = 17, scale = 17)
	public double getTiceaf() {
		return this.ticeaf;
	}

	public void setTiceaf(double ticeaf) {
		this.ticeaf = ticeaf;
	}

	@Column(name = "trea", nullable = false, precision = 17, scale = 17)
	public double getTrea() {
		return this.trea;
	}

	public void setTrea(double trea) {
		this.trea = trea;
	}

	@Column(name = "montointerespagado", nullable = false, precision = 17, scale = 17)
	public double getMontointerespagado() {
		return this.montointerespagado;
	}

	public void setMontointerespagado(double montointerespagado) {
		this.montointerespagado = montointerespagado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechavencimiento", nullable = false, length = 13)
	public Date getFechavencimiento() {
		return this.fechavencimiento;
	}

	public void setFechavencimiento(Date fechavencimiento) {
		this.fechavencimiento = fechavencimiento;
	}

	@Column(name = "monto", nullable = false, precision = 17, scale = 17)
	public double getMonto() {
		return this.monto;
	}

	public void setMonto(double monto) {
		this.monto = monto;
	}

	@Column(name = "itf", nullable = false, precision = 17, scale = 17)
	public double getItf() {
		return this.itf;
	}

	public void setItf(double itf) {
		this.itf = itf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaplazofijo")
	public Set getBeneficiariocuentas() {
		return this.beneficiariocuentas;
	}

	public void setBeneficiariocuentas(Set beneficiariocuentas) {
		this.beneficiariocuentas = beneficiariocuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cuentaplazofijo")
	public Set getTitularcuentas() {
		return this.titularcuentas;
	}

	public void setTitularcuentas(Set titularcuentas) {
		this.titularcuentas = titularcuentas;
	}

}
