package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Cuentaahorrohistorial generated by hbm2java
 */
@Entity
@Table(name = "cuentaahorrohistorial", schema = "cuentapersonal")
public class Cuentaahorrohistorial implements java.io.Serializable {

	private int idcuentaahorrohistorial;
	private Cuentaahorro cuentaahorro;
	private double tasainteres;
	private boolean estado;
	private int cantidadretirantes;

	public Cuentaahorrohistorial() {
	}

	public Cuentaahorrohistorial(int idcuentaahorrohistorial,
			Cuentaahorro cuentaahorro, double tasainteres, boolean estado,
			int cantidadretirantes) {
		this.idcuentaahorrohistorial = idcuentaahorrohistorial;
		this.cuentaahorro = cuentaahorro;
		this.tasainteres = tasainteres;
		this.estado = estado;
		this.cantidadretirantes = cantidadretirantes;
	}

	@Id
	@Column(name = "idcuentaahorrohistorial", unique = true, nullable = false)
	public int getIdcuentaahorrohistorial() {
		return this.idcuentaahorrohistorial;
	}

	public void setIdcuentaahorrohistorial(int idcuentaahorrohistorial) {
		this.idcuentaahorrohistorial = idcuentaahorrohistorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaahorro", nullable = false)
	public Cuentaahorro getCuentaahorro() {
		return this.cuentaahorro;
	}

	public void setCuentaahorro(Cuentaahorro cuentaahorro) {
		this.cuentaahorro = cuentaahorro;
	}

	@Column(name = "tasainteres", nullable = false, precision = 17, scale = 17)
	public double getTasainteres() {
		return this.tasainteres;
	}

	public void setTasainteres(double tasainteres) {
		this.tasainteres = tasainteres;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Column(name = "cantidadretirantes", nullable = false)
	public int getCantidadretirantes() {
		return this.cantidadretirantes;
	}

	public void setCantidadretirantes(int cantidadretirantes) {
		this.cantidadretirantes = cantidadretirantes;
	}

}
