package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadotargeta generated by hbm2java
 */
@Entity
@Table(name = "estadotargeta", schema = "cuentapersonal")
public class Estadotargeta implements java.io.Serializable {

	private int idestadotargeta;
	private String denominacion;
	private boolean estado;
	private String abreviatura;
	private Set tarjetadebitos = new HashSet(0);

	public Estadotargeta() {
	}

	public Estadotargeta(int idestadotargeta, String denominacion,
			boolean estado) {
		this.idestadotargeta = idestadotargeta;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Estadotargeta(int idestadotargeta, String denominacion,
			boolean estado, String abreviatura, Set tarjetadebitos) {
		this.idestadotargeta = idestadotargeta;
		this.denominacion = denominacion;
		this.estado = estado;
		this.abreviatura = abreviatura;
		this.tarjetadebitos = tarjetadebitos;
	}

	@Id
	@Column(name = "idestadotargeta", unique = true, nullable = false)
	public int getIdestadotargeta() {
		return this.idestadotargeta;
	}

	public void setIdestadotargeta(int idestadotargeta) {
		this.idestadotargeta = idestadotargeta;
	}

	@Column(name = "denominacion", nullable = false, length = 50)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@Column(name = "abreviatura", length = 50)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadotargeta")
	public Set getTarjetadebitos() {
		return this.tarjetadebitos;
	}

	public void setTarjetadebitos(Set tarjetadebitos) {
		this.tarjetadebitos = tarjetadebitos;
	}

}
