package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estadocuenta generated by hbm2java
 */
@Entity
@Table(name = "estadocuenta", schema = "cuentapersonal")
public class Estadocuenta implements java.io.Serializable {

	private int idestadocuenta;
	private String denominacion;
	private String abreviatura;
	private Boolean estado;
	private Set cuentaplazofijos = new HashSet(0);
	private Set cuentaahorros = new HashSet(0);
	private Set cuentacorrientes = new HashSet(0);

	public Estadocuenta() {
	}

	public Estadocuenta(int idestadocuenta, String denominacion) {
		this.idestadocuenta = idestadocuenta;
		this.denominacion = denominacion;
	}

	public Estadocuenta(int idestadocuenta, String denominacion,
			String abreviatura, Boolean estado, Set cuentaplazofijos,
			Set cuentaahorros, Set cuentacorrientes) {
		this.idestadocuenta = idestadocuenta;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.cuentaplazofijos = cuentaplazofijos;
		this.cuentaahorros = cuentaahorros;
		this.cuentacorrientes = cuentacorrientes;
	}

	@Id
	@Column(name = "idestadocuenta", unique = true, nullable = false)
	public int getIdestadocuenta() {
		return this.idestadocuenta;
	}

	public void setIdestadocuenta(int idestadocuenta) {
		this.idestadocuenta = idestadocuenta;
	}

	@Column(name = "denominacion", nullable = false, length = 20)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 3)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocuenta")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocuenta")
	public Set getCuentaahorros() {
		return this.cuentaahorros;
	}

	public void setCuentaahorros(Set cuentaahorros) {
		this.cuentaahorros = cuentaahorros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estadocuenta")
	public Set getCuentacorrientes() {
		return this.cuentacorrientes;
	}

	public void setCuentacorrientes(Set cuentacorrientes) {
		this.cuentacorrientes = cuentacorrientes;
	}

}
