package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Frecuenciacapitalizacion generated by hbm2java
 */
@Entity
@Table(name = "frecuenciacapitalizacion", schema = "cuentapersonal")
public class Frecuenciacapitalizacion implements java.io.Serializable {

	private int idfrecuenciacapitalizacion;
	private String denomicacion;
	private int numerodias;
	private boolean estado;
	private Set cuentaplazofijos = new HashSet(0);

	public Frecuenciacapitalizacion() {
	}

	public Frecuenciacapitalizacion(int idfrecuenciacapitalizacion,
			String denomicacion, int numerodias, boolean estado) {
		this.idfrecuenciacapitalizacion = idfrecuenciacapitalizacion;
		this.denomicacion = denomicacion;
		this.numerodias = numerodias;
		this.estado = estado;
	}

	public Frecuenciacapitalizacion(int idfrecuenciacapitalizacion,
			String denomicacion, int numerodias, boolean estado,
			Set cuentaplazofijos) {
		this.idfrecuenciacapitalizacion = idfrecuenciacapitalizacion;
		this.denomicacion = denomicacion;
		this.numerodias = numerodias;
		this.estado = estado;
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@Id
	@Column(name = "idfrecuenciacapitalizacion", unique = true, nullable = false)
	public int getIdfrecuenciacapitalizacion() {
		return this.idfrecuenciacapitalizacion;
	}

	public void setIdfrecuenciacapitalizacion(int idfrecuenciacapitalizacion) {
		this.idfrecuenciacapitalizacion = idfrecuenciacapitalizacion;
	}

	@Column(name = "denomicacion", nullable = false, length = 30)
	public String getDenomicacion() {
		return this.denomicacion;
	}

	public void setDenomicacion(String denomicacion) {
		this.denomicacion = denomicacion;
	}

	@Column(name = "numerodias", nullable = false)
	public int getNumerodias() {
		return this.numerodias;
	}

	public void setNumerodias(int numerodias) {
		this.numerodias = numerodias;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frecuenciacapitalizacion")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

}
