package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personajuridica generated by hbm2java
 */
@Entity
@Table(name = "personajuridica", schema = "persona")
public class Personajuridica implements java.io.Serializable {

	private String ruc;
	private Personanatural personanatural;
	private Tipoempresa tipoempresa;
	private String razonsocial;
	private String nombrecomercial;
	private Date fechaconstitucion;
	private String actividadprincipal;
	private String telefono;
	private String celular;
	private String email;
	private String direccion;
	private String referencia;
	private Boolean finsocial;
	private Set accionistas = new HashSet(0);
	private Personajuridicacliente personajuridicacliente;

	public Personajuridica() {
	}

	public Personajuridica(String ruc, Personanatural personanatural,
			Tipoempresa tipoempresa, String razonsocial, Date fechaconstitucion) {
		this.ruc = ruc;
		this.personanatural = personanatural;
		this.tipoempresa = tipoempresa;
		this.razonsocial = razonsocial;
		this.fechaconstitucion = fechaconstitucion;
	}

	public Personajuridica(String ruc, Personanatural personanatural,
			Tipoempresa tipoempresa, String razonsocial,
			String nombrecomercial, Date fechaconstitucion,
			String actividadprincipal, String telefono, String celular,
			String email, String direccion, String referencia,
			Boolean finsocial, Set accionistas,
			Personajuridicacliente personajuridicacliente) {
		this.ruc = ruc;
		this.personanatural = personanatural;
		this.tipoempresa = tipoempresa;
		this.razonsocial = razonsocial;
		this.nombrecomercial = nombrecomercial;
		this.fechaconstitucion = fechaconstitucion;
		this.actividadprincipal = actividadprincipal;
		this.telefono = telefono;
		this.celular = celular;
		this.email = email;
		this.direccion = direccion;
		this.referencia = referencia;
		this.finsocial = finsocial;
		this.accionistas = accionistas;
		this.personajuridicacliente = personajuridicacliente;
	}

	@Id
	@Column(name = "ruc", unique = true, nullable = false, length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dnirepresentantelegal", nullable = false)
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtipoempresa", nullable = false)
	public Tipoempresa getTipoempresa() {
		return this.tipoempresa;
	}

	public void setTipoempresa(Tipoempresa tipoempresa) {
		this.tipoempresa = tipoempresa;
	}

	@Column(name = "razonsocial", nullable = false, length = 50)
	public String getRazonsocial() {
		return this.razonsocial;
	}

	public void setRazonsocial(String razonsocial) {
		this.razonsocial = razonsocial;
	}

	@Column(name = "nombrecomercial", length = 50)
	public String getNombrecomercial() {
		return this.nombrecomercial;
	}

	public void setNombrecomercial(String nombrecomercial) {
		this.nombrecomercial = nombrecomercial;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaconstitucion", nullable = false, length = 13)
	public Date getFechaconstitucion() {
		return this.fechaconstitucion;
	}

	public void setFechaconstitucion(Date fechaconstitucion) {
		this.fechaconstitucion = fechaconstitucion;
	}

	@Column(name = "actividadprincipal", length = 50)
	public String getActividadprincipal() {
		return this.actividadprincipal;
	}

	public void setActividadprincipal(String actividadprincipal) {
		this.actividadprincipal = actividadprincipal;
	}

	@Column(name = "telefono", length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular", length = 30)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "referencia", length = 100)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "finsocial")
	public Boolean getFinsocial() {
		return this.finsocial;
	}

	public void setFinsocial(Boolean finsocial) {
		this.finsocial = finsocial;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajuridica")
	public Set getAccionistas() {
		return this.accionistas;
	}

	public void setAccionistas(Set accionistas) {
		this.accionistas = accionistas;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personajuridica")
	public Personajuridicacliente getPersonajuridicacliente() {
		return this.personajuridicacliente;
	}

	public void setPersonajuridicacliente(
			Personajuridicacliente personajuridicacliente) {
		this.personajuridicacliente = personajuridicacliente;
	}

}
