package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Personanatural generated by hbm2java
 */
@Entity
@Table(name = "personanatural", schema = "persona")
public class Personanatural implements java.io.Serializable {

	private String dni;
	private Sexo sexo;
	private Estadocivil estadocivil;
	private String apellidopaterno;
	private String apellidomaterno;
	private String nombres;
	private Date fechanacimiento;
	private String ocupacion;
	private String telefono;
	private String celular;
	private String email;
	private String direccion;
	private String referencia;
	private String firma;
	private Personanaturalcliente personanaturalcliente;
	private Set titularcuentas = new HashSet(0);
	private Set personajuridicas = new HashSet(0);
	private Set beneficiariocuentas = new HashSet(0);
	private Set accionistas = new HashSet(0);

	public Personanatural() {
	}

	public Personanatural(String dni, Sexo sexo, String apellidopaterno,
			String apellidomaterno, String nombres, Date fechanacimiento) {
		this.dni = dni;
		this.sexo = sexo;
		this.apellidopaterno = apellidopaterno;
		this.apellidomaterno = apellidomaterno;
		this.nombres = nombres;
		this.fechanacimiento = fechanacimiento;
	}

	public Personanatural(String dni, Sexo sexo, Estadocivil estadocivil,
			String apellidopaterno, String apellidomaterno, String nombres,
			Date fechanacimiento, String ocupacion, String telefono,
			String celular, String email, String direccion, String referencia,
			String firma, Personanaturalcliente personanaturalcliente,
			Set titularcuentas, Set personajuridicas, Set beneficiariocuentas,
			Set accionistas) {
		this.dni = dni;
		this.sexo = sexo;
		this.estadocivil = estadocivil;
		this.apellidopaterno = apellidopaterno;
		this.apellidomaterno = apellidomaterno;
		this.nombres = nombres;
		this.fechanacimiento = fechanacimiento;
		this.ocupacion = ocupacion;
		this.telefono = telefono;
		this.celular = celular;
		this.email = email;
		this.direccion = direccion;
		this.referencia = referencia;
		this.firma = firma;
		this.personanaturalcliente = personanaturalcliente;
		this.titularcuentas = titularcuentas;
		this.personajuridicas = personajuridicas;
		this.beneficiariocuentas = beneficiariocuentas;
		this.accionistas = accionistas;
	}

	@Id
	@Column(name = "dni", unique = true, nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsexo", nullable = false)
	public Sexo getSexo() {
		return this.sexo;
	}

	public void setSexo(Sexo sexo) {
		this.sexo = sexo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestadocivil")
	public Estadocivil getEstadocivil() {
		return this.estadocivil;
	}

	public void setEstadocivil(Estadocivil estadocivil) {
		this.estadocivil = estadocivil;
	}

	@Column(name = "apellidopaterno", nullable = false, length = 40)
	public String getApellidopaterno() {
		return this.apellidopaterno;
	}

	public void setApellidopaterno(String apellidopaterno) {
		this.apellidopaterno = apellidopaterno;
	}

	@Column(name = "apellidomaterno", nullable = false, length = 40)
	public String getApellidomaterno() {
		return this.apellidomaterno;
	}

	public void setApellidomaterno(String apellidomaterno) {
		this.apellidomaterno = apellidomaterno;
	}

	@Column(name = "nombres", nullable = false, length = 50)
	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechanacimiento", nullable = false, length = 13)
	public Date getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(Date fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	@Column(name = "ocupacion", length = 50)
	public String getOcupacion() {
		return this.ocupacion;
	}

	public void setOcupacion(String ocupacion) {
		this.ocupacion = ocupacion;
	}

	@Column(name = "telefono", length = 30)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "celular", length = 30)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "direccion", length = 200)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "referencia", length = 100)
	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	@Column(name = "firma", length = 200)
	public String getFirma() {
		return this.firma;
	}

	public void setFirma(String firma) {
		this.firma = firma;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Personanaturalcliente getPersonanaturalcliente() {
		return this.personanaturalcliente;
	}

	public void setPersonanaturalcliente(
			Personanaturalcliente personanaturalcliente) {
		this.personanaturalcliente = personanaturalcliente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Set getTitularcuentas() {
		return this.titularcuentas;
	}

	public void setTitularcuentas(Set titularcuentas) {
		this.titularcuentas = titularcuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Set getPersonajuridicas() {
		return this.personajuridicas;
	}

	public void setPersonajuridicas(Set personajuridicas) {
		this.personajuridicas = personajuridicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Set getBeneficiariocuentas() {
		return this.beneficiariocuentas;
	}

	public void setBeneficiariocuentas(Set beneficiariocuentas) {
		this.beneficiariocuentas = beneficiariocuentas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanatural")
	public Set getAccionistas() {
		return this.accionistas;
	}

	public void setAccionistas(Set accionistas) {
		this.accionistas = accionistas;
	}

}
