package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Personanaturalcliente generated by hbm2java
 */
@Entity
@Table(name = "personanaturalcliente", schema = "cliente")
public class Personanaturalcliente implements java.io.Serializable {

	private String dni;
	private Personanatural personanatural;
	private Set cuentacorrientes = new HashSet(0);
	private Set cuentaahorros = new HashSet(0);
	private Set cuentaplazofijos = new HashSet(0);

	public Personanaturalcliente() {
	}

	public Personanaturalcliente(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	public Personanaturalcliente(Personanatural personanatural,
			Set cuentacorrientes, Set cuentaahorros, Set cuentaplazofijos) {
		this.personanatural = personanatural;
		this.cuentacorrientes = cuentacorrientes;
		this.cuentaahorros = cuentaahorros;
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personanatural"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "dni", unique = true, nullable = false, length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanaturalcliente")
	public Set getCuentacorrientes() {
		return this.cuentacorrientes;
	}

	public void setCuentacorrientes(Set cuentacorrientes) {
		this.cuentacorrientes = cuentacorrientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanaturalcliente")
	public Set getCuentaahorros() {
		return this.cuentaahorros;
	}

	public void setCuentaahorros(Set cuentaahorros) {
		this.cuentaahorros = cuentaahorros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personanaturalcliente")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

}
