package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Personajuridicacliente generated by hbm2java
 */
@Entity
@Table(name = "personajuridicacliente", schema = "cliente")
public class Personajuridicacliente implements java.io.Serializable {

	private String ruc;
	private Personajuridica personajuridica;
	private Set cuentacorrientes = new HashSet(0);
	private Set cuentaahorros = new HashSet(0);
	private Set cuentaplazofijos = new HashSet(0);

	public Personajuridicacliente() {
	}

	public Personajuridicacliente(Personajuridica personajuridica) {
		this.personajuridica = personajuridica;
	}

	public Personajuridicacliente(Personajuridica personajuridica,
			Set cuentacorrientes, Set cuentaahorros, Set cuentaplazofijos) {
		this.personajuridica = personajuridica;
		this.cuentacorrientes = cuentacorrientes;
		this.cuentaahorros = cuentaahorros;
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personajuridica"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "ruc", unique = true, nullable = false, length = 11)
	public String getRuc() {
		return this.ruc;
	}

	public void setRuc(String ruc) {
		this.ruc = ruc;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personajuridica getPersonajuridica() {
		return this.personajuridica;
	}

	public void setPersonajuridica(Personajuridica personajuridica) {
		this.personajuridica = personajuridica;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajuridicacliente")
	public Set getCuentacorrientes() {
		return this.cuentacorrientes;
	}

	public void setCuentacorrientes(Set cuentacorrientes) {
		this.cuentacorrientes = cuentacorrientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajuridicacliente")
	public Set getCuentaahorros() {
		return this.cuentaahorros;
	}

	public void setCuentaahorros(Set cuentaahorros) {
		this.cuentaahorros = cuentaahorros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "personajuridicacliente")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

}
