package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Retirointeres generated by hbm2java
 */
@Entity
@Table(name = "retirointeres", schema = "cuentapersonal")
public class Retirointeres implements java.io.Serializable {

	private int idretirointeres;
	private String denominacion;
	private String abreviatura;
	private boolean estado;
	private Set cuentaplazofijos = new HashSet(0);

	public Retirointeres() {
	}

	public Retirointeres(int idretirointeres, String denominacion,
			boolean estado) {
		this.idretirointeres = idretirointeres;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Retirointeres(int idretirointeres, String denominacion,
			String abreviatura, boolean estado, Set cuentaplazofijos) {
		this.idretirointeres = idretirointeres;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@Id
	@Column(name = "idretirointeres", unique = true, nullable = false)
	public int getIdretirointeres() {
		return this.idretirointeres;
	}

	public void setIdretirointeres(int idretirointeres) {
		this.idretirointeres = idretirointeres;
	}

	@Column(name = "denominacion", nullable = false, length = 50)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 5)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "retirointeres")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

}
