package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sexo generated by hbm2java
 */
@Entity
@Table(name = "sexo", schema = "maestro")
public class Sexo implements java.io.Serializable {

	private int idsexo;
	private String denominacion;
	private Character abreviatura;
	private Boolean estado;
	private Set personanaturals = new HashSet(0);

	public Sexo() {
	}

	public Sexo(int idsexo) {
		this.idsexo = idsexo;
	}

	public Sexo(int idsexo, String denominacion, Character abreviatura,
			Boolean estado, Set personanaturals) {
		this.idsexo = idsexo;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.personanaturals = personanaturals;
	}

	@Id
	@Column(name = "idsexo", unique = true, nullable = false)
	public int getIdsexo() {
		return this.idsexo;
	}

	public void setIdsexo(int idsexo) {
		this.idsexo = idsexo;
	}

	@Column(name = "denominacion", length = 15)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 1)
	public Character getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(Character abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexo")
	public Set getPersonanaturals() {
		return this.personanaturals;
	}

	public void setPersonanaturals(Set personanaturals) {
		this.personanaturals = personanaturals;
	}

}
