package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sucursal generated by hbm2java
 */
@Entity
@Table(name = "sucursal", schema = "sucursal")
public class Sucursal implements java.io.Serializable {

	private int idsucursal;
	private Ubigeo ubigeo;
	private String denominacion;
	private String abreviatura;
	private boolean estado;
	private Set chequeras = new HashSet(0);

	public Sucursal() {
	}

	public Sucursal(int idsucursal, Ubigeo ubigeo, String denominacion,
			boolean estado) {
		this.idsucursal = idsucursal;
		this.ubigeo = ubigeo;
		this.denominacion = denominacion;
		this.estado = estado;
	}

	public Sucursal(int idsucursal, Ubigeo ubigeo, String denominacion,
			String abreviatura, boolean estado, Set chequeras) {
		this.idsucursal = idsucursal;
		this.ubigeo = ubigeo;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.chequeras = chequeras;
	}

	@Id
	@Column(name = "idsucursal", unique = true, nullable = false)
	public int getIdsucursal() {
		return this.idsucursal;
	}

	public void setIdsucursal(int idsucursal) {
		this.idsucursal = idsucursal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idubigeo", nullable = false)
	public Ubigeo getUbigeo() {
		return this.ubigeo;
	}

	public void setUbigeo(Ubigeo ubigeo) {
		this.ubigeo = ubigeo;
	}

	@Column(name = "denominacion", nullable = false, length = 150)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 10)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sucursal")
	public Set getChequeras() {
		return this.chequeras;
	}

	public void setChequeras(Set chequeras) {
		this.chequeras = chequeras;
	}

}
