package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Targetadebitoasignadocuentacorriente generated by hbm2java
 */
@Entity
@Table(name = "targetadebitoasignadocuentacorriente", schema = "cuentapersonal")
public class Targetadebitoasignadocuentacorriente implements
		java.io.Serializable {

	private TargetadebitoasignadocuentacorrienteId id;
	private Cuentacorriente cuentacorriente;
	private Tarjetadebito tarjetadebito;
	private int fechaactiva;
	private Integer fechainactiva;
	private boolean estado;

	public Targetadebitoasignadocuentacorriente() {
	}

	public Targetadebitoasignadocuentacorriente(
			TargetadebitoasignadocuentacorrienteId id,
			Cuentacorriente cuentacorriente, Tarjetadebito tarjetadebito,
			int fechaactiva, boolean estado) {
		this.id = id;
		this.cuentacorriente = cuentacorriente;
		this.tarjetadebito = tarjetadebito;
		this.fechaactiva = fechaactiva;
		this.estado = estado;
	}

	public Targetadebitoasignadocuentacorriente(
			TargetadebitoasignadocuentacorrienteId id,
			Cuentacorriente cuentacorriente, Tarjetadebito tarjetadebito,
			int fechaactiva, Integer fechainactiva, boolean estado) {
		this.id = id;
		this.cuentacorriente = cuentacorriente;
		this.tarjetadebito = tarjetadebito;
		this.fechaactiva = fechaactiva;
		this.fechainactiva = fechainactiva;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numerocuentacorriente", column = @Column(name = "numerocuentacorriente", nullable = false, length = 14)),
			@AttributeOverride(name = "numerotargeta", column = @Column(name = "numerotargeta", nullable = false, length = 16)) })
	public TargetadebitoasignadocuentacorrienteId getId() {
		return this.id;
	}

	public void setId(TargetadebitoasignadocuentacorrienteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentacorriente", nullable = false, insertable = false, updatable = false)
	public Cuentacorriente getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(Cuentacorriente cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotargeta", nullable = false, insertable = false, updatable = false)
	public Tarjetadebito getTarjetadebito() {
		return this.tarjetadebito;
	}

	public void setTarjetadebito(Tarjetadebito tarjetadebito) {
		this.tarjetadebito = tarjetadebito;
	}

	@Column(name = "fechaactiva", nullable = false)
	public int getFechaactiva() {
		return this.fechaactiva;
	}

	public void setFechaactiva(int fechaactiva) {
		this.fechaactiva = fechaactiva;
	}

	@Column(name = "fechainactiva")
	public Integer getFechainactiva() {
		return this.fechainactiva;
	}

	public void setFechainactiva(Integer fechainactiva) {
		this.fechainactiva = fechainactiva;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
