package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TargetadebitoasignadocuentacorrienteId generated by hbm2java
 */
@Embeddable
public class TargetadebitoasignadocuentacorrienteId implements
		java.io.Serializable {

	private String numerocuentacorriente;
	private String numerotargeta;

	public TargetadebitoasignadocuentacorrienteId() {
	}

	public TargetadebitoasignadocuentacorrienteId(String numerocuentacorriente,
			String numerotargeta) {
		this.numerocuentacorriente = numerocuentacorriente;
		this.numerotargeta = numerotargeta;
	}

	@Column(name = "numerocuentacorriente", nullable = false, length = 14)
	public String getNumerocuentacorriente() {
		return this.numerocuentacorriente;
	}

	public void setNumerocuentacorriente(String numerocuentacorriente) {
		this.numerocuentacorriente = numerocuentacorriente;
	}

	@Column(name = "numerotargeta", nullable = false, length = 16)
	public String getNumerotargeta() {
		return this.numerotargeta;
	}

	public void setNumerotargeta(String numerotargeta) {
		this.numerotargeta = numerotargeta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TargetadebitoasignadocuentacorrienteId))
			return false;
		TargetadebitoasignadocuentacorrienteId castOther = (TargetadebitoasignadocuentacorrienteId) other;

		return ((this.getNumerocuentacorriente() == castOther
				.getNumerocuentacorriente()) || (this
				.getNumerocuentacorriente() != null
				&& castOther.getNumerocuentacorriente() != null && this
				.getNumerocuentacorriente().equals(
						castOther.getNumerocuentacorriente())))
				&& ((this.getNumerotargeta() == castOther.getNumerotargeta()) || (this
						.getNumerotargeta() != null
						&& castOther.getNumerotargeta() != null && this
						.getNumerotargeta()
						.equals(castOther.getNumerotargeta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumerocuentacorriente() == null ? 0 : this
						.getNumerocuentacorriente().hashCode());
		result = 37
				* result
				+ (getNumerotargeta() == null ? 0 : this.getNumerotargeta()
						.hashCode());
		return result;
	}

}
