package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tarjetadebitoasignadocuentaahorro generated by hbm2java
 */
@Entity
@Table(name = "tarjetadebitoasignadocuentaahorro", schema = "cuentapersonal")
public class Tarjetadebitoasignadocuentaahorro implements java.io.Serializable {

	private TarjetadebitoasignadocuentaahorroId id;
	private Cuentaahorro cuentaahorro;
	private Tarjetadebito tarjetadebito;
	private Date fechainanctiva;
	private int fechaactiva;
	private boolean estado;

	public Tarjetadebitoasignadocuentaahorro() {
	}

	public Tarjetadebitoasignadocuentaahorro(
			TarjetadebitoasignadocuentaahorroId id, Cuentaahorro cuentaahorro,
			Tarjetadebito tarjetadebito, int fechaactiva, boolean estado) {
		this.id = id;
		this.cuentaahorro = cuentaahorro;
		this.tarjetadebito = tarjetadebito;
		this.fechaactiva = fechaactiva;
		this.estado = estado;
	}

	public Tarjetadebitoasignadocuentaahorro(
			TarjetadebitoasignadocuentaahorroId id, Cuentaahorro cuentaahorro,
			Tarjetadebito tarjetadebito, Date fechainanctiva, int fechaactiva,
			boolean estado) {
		this.id = id;
		this.cuentaahorro = cuentaahorro;
		this.tarjetadebito = tarjetadebito;
		this.fechainanctiva = fechainanctiva;
		this.fechaactiva = fechaactiva;
		this.estado = estado;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "numerocuentaahorro", column = @Column(name = "numerocuentaahorro", nullable = false, length = 14)),
			@AttributeOverride(name = "numerotargeta", column = @Column(name = "numerotargeta", nullable = false, length = 16)) })
	public TarjetadebitoasignadocuentaahorroId getId() {
		return this.id;
	}

	public void setId(TarjetadebitoasignadocuentaahorroId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaahorro", nullable = false, insertable = false, updatable = false)
	public Cuentaahorro getCuentaahorro() {
		return this.cuentaahorro;
	}

	public void setCuentaahorro(Cuentaahorro cuentaahorro) {
		this.cuentaahorro = cuentaahorro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerotargeta", nullable = false, insertable = false, updatable = false)
	public Tarjetadebito getTarjetadebito() {
		return this.tarjetadebito;
	}

	public void setTarjetadebito(Tarjetadebito tarjetadebito) {
		this.tarjetadebito = tarjetadebito;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainanctiva", length = 13)
	public Date getFechainanctiva() {
		return this.fechainanctiva;
	}

	public void setFechainanctiva(Date fechainanctiva) {
		this.fechainanctiva = fechainanctiva;
	}

	@Column(name = "fechaactiva", nullable = false)
	public int getFechaactiva() {
		return this.fechaactiva;
	}

	public void setFechaactiva(int fechaactiva) {
		this.fechaactiva = fechaactiva;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
