package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TarjetadebitoasignadocuentaahorroId generated by hbm2java
 */
@Embeddable
public class TarjetadebitoasignadocuentaahorroId implements
		java.io.Serializable {

	private String numerocuentaahorro;
	private String numerotargeta;

	public TarjetadebitoasignadocuentaahorroId() {
	}

	public TarjetadebitoasignadocuentaahorroId(String numerocuentaahorro,
			String numerotargeta) {
		this.numerocuentaahorro = numerocuentaahorro;
		this.numerotargeta = numerotargeta;
	}

	@Column(name = "numerocuentaahorro", nullable = false, length = 14)
	public String getNumerocuentaahorro() {
		return this.numerocuentaahorro;
	}

	public void setNumerocuentaahorro(String numerocuentaahorro) {
		this.numerocuentaahorro = numerocuentaahorro;
	}

	@Column(name = "numerotargeta", nullable = false, length = 16)
	public String getNumerotargeta() {
		return this.numerotargeta;
	}

	public void setNumerotargeta(String numerotargeta) {
		this.numerotargeta = numerotargeta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TarjetadebitoasignadocuentaahorroId))
			return false;
		TarjetadebitoasignadocuentaahorroId castOther = (TarjetadebitoasignadocuentaahorroId) other;

		return ((this.getNumerocuentaahorro() == castOther
				.getNumerocuentaahorro()) || (this.getNumerocuentaahorro() != null
				&& castOther.getNumerocuentaahorro() != null && this
				.getNumerocuentaahorro().equals(
						castOther.getNumerocuentaahorro())))
				&& ((this.getNumerotargeta() == castOther.getNumerotargeta()) || (this
						.getNumerotargeta() != null
						&& castOther.getNumerotargeta() != null && this
						.getNumerotargeta()
						.equals(castOther.getNumerotargeta())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getNumerocuentaahorro() == null ? 0 : this
						.getNumerocuentaahorro().hashCode());
		result = 37
				* result
				+ (getNumerotargeta() == null ? 0 : this.getNumerotargeta()
						.hashCode());
		return result;
	}

}
