package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipomoneda generated by hbm2java
 */
@Entity
@Table(name = "tipomoneda", schema = "maestro")
public class Tipomoneda implements java.io.Serializable {

	private int idtipomoneda;
	private String denominacion;
	private String abreviatura;
	private Boolean estado;
	private Set cuentaplazofijos = new HashSet(0);
	private Set cuentaahorros = new HashSet(0);
	private Set cuentacorrientes = new HashSet(0);

	public Tipomoneda() {
	}

	public Tipomoneda(int idtipomoneda) {
		this.idtipomoneda = idtipomoneda;
	}

	public Tipomoneda(int idtipomoneda, String denominacion,
			String abreviatura, Boolean estado, Set cuentaplazofijos,
			Set cuentaahorros, Set cuentacorrientes) {
		this.idtipomoneda = idtipomoneda;
		this.denominacion = denominacion;
		this.abreviatura = abreviatura;
		this.estado = estado;
		this.cuentaplazofijos = cuentaplazofijos;
		this.cuentaahorros = cuentaahorros;
		this.cuentacorrientes = cuentacorrientes;
	}

	@Id
	@Column(name = "idtipomoneda", unique = true, nullable = false)
	public int getIdtipomoneda() {
		return this.idtipomoneda;
	}

	public void setIdtipomoneda(int idtipomoneda) {
		this.idtipomoneda = idtipomoneda;
	}

	@Column(name = "denominacion", length = 35)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "abreviatura", length = 3)
	public String getAbreviatura() {
		return this.abreviatura;
	}

	public void setAbreviatura(String abreviatura) {
		this.abreviatura = abreviatura;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomoneda")
	public Set getCuentaplazofijos() {
		return this.cuentaplazofijos;
	}

	public void setCuentaplazofijos(Set cuentaplazofijos) {
		this.cuentaplazofijos = cuentaplazofijos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomoneda")
	public Set getCuentaahorros() {
		return this.cuentaahorros;
	}

	public void setCuentaahorros(Set cuentaahorros) {
		this.cuentaahorros = cuentaahorros;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipomoneda")
	public Set getCuentacorrientes() {
		return this.cuentacorrientes;
	}

	public void setCuentacorrientes(Set cuentacorrientes) {
		this.cuentacorrientes = cuentacorrientes;
	}

}
