package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoempresa generated by hbm2java
 */
@Entity
@Table(name = "tipoempresa", schema = "persona")
public class Tipoempresa implements java.io.Serializable {

	private int idtipoempresa;
	private String denominacion;
	private Boolean estado;
	private Set personajuridicas = new HashSet(0);

	public Tipoempresa() {
	}

	public Tipoempresa(int idtipoempresa) {
		this.idtipoempresa = idtipoempresa;
	}

	public Tipoempresa(int idtipoempresa, String denominacion, Boolean estado,
			Set personajuridicas) {
		this.idtipoempresa = idtipoempresa;
		this.denominacion = denominacion;
		this.estado = estado;
		this.personajuridicas = personajuridicas;
	}

	@Id
	@Column(name = "idtipoempresa", unique = true, nullable = false)
	public int getIdtipoempresa() {
		return this.idtipoempresa;
	}

	public void setIdtipoempresa(int idtipoempresa) {
		this.idtipoempresa = idtipoempresa;
	}

	@Column(name = "denominacion", length = 50)
	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoempresa")
	public Set getPersonajuridicas() {
		return this.personajuridicas;
	}

	public void setPersonajuridicas(Set personajuridicas) {
		this.personajuridicas = personajuridicas;
	}

}
