package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Titularcuenta generated by hbm2java
 */
@Entity
@Table(name = "titularcuenta", schema = "cuentapersonal")
public class Titularcuenta implements java.io.Serializable {

	private int idtitularcuenta;
	private Cuentaplazofijo cuentaplazofijo;
	private Cuentacorriente cuentacorriente;
	private Personanatural personanatural;
	private Cuentaahorro cuentaahorro;
	private Set titularcuentahistorials = new HashSet(0);

	public Titularcuenta() {
	}

	public Titularcuenta(int idtitularcuenta, Personanatural personanatural) {
		this.idtitularcuenta = idtitularcuenta;
		this.personanatural = personanatural;
	}

	public Titularcuenta(int idtitularcuenta, Cuentaplazofijo cuentaplazofijo,
			Cuentacorriente cuentacorriente, Personanatural personanatural,
			Cuentaahorro cuentaahorro, Set titularcuentahistorials) {
		this.idtitularcuenta = idtitularcuenta;
		this.cuentaplazofijo = cuentaplazofijo;
		this.cuentacorriente = cuentacorriente;
		this.personanatural = personanatural;
		this.cuentaahorro = cuentaahorro;
		this.titularcuentahistorials = titularcuentahistorials;
	}

	@Id
	@Column(name = "idtitularcuenta", unique = true, nullable = false)
	public int getIdtitularcuenta() {
		return this.idtitularcuenta;
	}

	public void setIdtitularcuenta(int idtitularcuenta) {
		this.idtitularcuenta = idtitularcuenta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaplazofijo")
	public Cuentaplazofijo getCuentaplazofijo() {
		return this.cuentaplazofijo;
	}

	public void setCuentaplazofijo(Cuentaplazofijo cuentaplazofijo) {
		this.cuentaplazofijo = cuentaplazofijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentacorriente")
	public Cuentacorriente getCuentacorriente() {
		return this.cuentacorriente;
	}

	public void setCuentacorriente(Cuentacorriente cuentacorriente) {
		this.cuentacorriente = cuentacorriente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dni", nullable = false)
	public Personanatural getPersonanatural() {
		return this.personanatural;
	}

	public void setPersonanatural(Personanatural personanatural) {
		this.personanatural = personanatural;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numerocuentaahorro")
	public Cuentaahorro getCuentaahorro() {
		return this.cuentaahorro;
	}

	public void setCuentaahorro(Cuentaahorro cuentaahorro) {
		this.cuentaahorro = cuentaahorro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "titularcuenta")
	public Set getTitularcuentahistorials() {
		return this.titularcuentahistorials;
	}

	public void setTitularcuentahistorials(Set titularcuentahistorials) {
		this.titularcuentahistorials = titularcuentahistorials;
	}

}
