package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titularcuentahistorial generated by hbm2java
 */
@Entity
@Table(name = "titularcuentahistorial", schema = "cuentapersonal")
public class Titularcuentahistorial implements java.io.Serializable {

	private int idtitularcuentahistorial;
	private Titularcuenta titularcuenta;
	private Date fechaactiva;
	private Date fechainactiva;
	private boolean estado;

	public Titularcuentahistorial() {
	}

	public Titularcuentahistorial(int idtitularcuentahistorial,
			Titularcuenta titularcuenta, Date fechaactiva, boolean estado) {
		this.idtitularcuentahistorial = idtitularcuentahistorial;
		this.titularcuenta = titularcuenta;
		this.fechaactiva = fechaactiva;
		this.estado = estado;
	}

	public Titularcuentahistorial(int idtitularcuentahistorial,
			Titularcuenta titularcuenta, Date fechaactiva, Date fechainactiva,
			boolean estado) {
		this.idtitularcuentahistorial = idtitularcuentahistorial;
		this.titularcuenta = titularcuenta;
		this.fechaactiva = fechaactiva;
		this.fechainactiva = fechainactiva;
		this.estado = estado;
	}

	@Id
	@Column(name = "idtitularcuentahistorial", unique = true, nullable = false)
	public int getIdtitularcuentahistorial() {
		return this.idtitularcuentahistorial;
	}

	public void setIdtitularcuentahistorial(int idtitularcuentahistorial) {
		this.idtitularcuentahistorial = idtitularcuentahistorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idtitularcuenta", nullable = false)
	public Titularcuenta getTitularcuenta() {
		return this.titularcuenta;
	}

	public void setTitularcuenta(Titularcuenta titularcuenta) {
		this.titularcuenta = titularcuenta;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaactiva", nullable = false, length = 13)
	public Date getFechaactiva() {
		return this.fechaactiva;
	}

	public void setFechaactiva(Date fechaactiva) {
		this.fechaactiva = fechaactiva;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechainactiva", length = 13)
	public Date getFechainactiva() {
		return this.fechainactiva;
	}

	public void setFechainactiva(Date fechainactiva) {
		this.fechainactiva = fechainactiva;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

}
