package org.ventura.model;

// Generated 02-sep-2013 11:26:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ubigeo generated by hbm2java
 */
@Entity
@Table(name = "ubigeo", schema = "maestro")
public class Ubigeo implements java.io.Serializable {

	private String idubigeo;
	private String departamento;
	private String provincia;
	private String distrito;
	private boolean estado;
	private Set sucursals = new HashSet(0);

	public Ubigeo() {
	}

	public Ubigeo(String idubigeo, String provincia, String distrito,
			boolean estado) {
		this.idubigeo = idubigeo;
		this.provincia = provincia;
		this.distrito = distrito;
		this.estado = estado;
	}

	public Ubigeo(String idubigeo, String departamento, String provincia,
			String distrito, boolean estado, Set sucursals) {
		this.idubigeo = idubigeo;
		this.departamento = departamento;
		this.provincia = provincia;
		this.distrito = distrito;
		this.estado = estado;
		this.sucursals = sucursals;
	}

	@Id
	@Column(name = "idubigeo", unique = true, nullable = false, length = 6)
	public String getIdubigeo() {
		return this.idubigeo;
	}

	public void setIdubigeo(String idubigeo) {
		this.idubigeo = idubigeo;
	}

	@Column(name = "departamento", length = 70)
	public String getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(String departamento) {
		this.departamento = departamento;
	}

	@Column(name = "provincia", nullable = false, length = 70)
	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	@Column(name = "distrito", nullable = false, length = 70)
	public String getDistrito() {
		return this.distrito;
	}

	public void setDistrito(String distrito) {
		this.distrito = distrito;
	}

	@Column(name = "estado", nullable = false)
	public boolean isEstado() {
		return this.estado;
	}

	public void setEstado(boolean estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubigeo")
	public Set getSucursals() {
		return this.sucursals;
	}

	public void setSucursals(Set sucursals) {
		this.sucursals = sucursals;
	}

}
